import { createStore } from "vuex";

export default createStore({
  state: {
    languages: {
      english: {
        my_profession: "Fullstack Developer",
        profile_details: "Profile Details",
        skills: {
          skill: "Skills",
          skills: [
            "Visual Studio Code",
            "HTML",
            "CSS",
            "JavaScript",
            "Vue Js 3",
            "Vue Router 4",
            "Vuex 4",
            "PHP 8",
            "Laravel 8",
            "MySql",
            "MariaDB",
            "Npm",
            "Composer",
            "Packagist",
            "Rest API",
            "Git",
            "cPanel",
            "Cron Job",
            "POO",
            "XML",
            "JSON",
            "ECMAScript",
            "UI",
            "UX",
          ],
        },
        about: {
          about: "About me",
          address: {
            from: {
              from: "I'm from",
              city: "Gramado RS, BR",
              google_maps: "https://goo.gl/maps/GH2JP18Sbxo4axmVA",
            },
            current: {
              lives_in: "I live in",
              city: "Rome, IT",
              google_maps: "https://goo.gl/maps/Hc7UpuLZ2FjeEmLo9",
            },
          },
          work_at: {
            work_at: "I work at",
            company: "Sellmasters",
            site: "https://www.sellmasters.it/",
          },
        },
        social_media: "Social Media",
      },
      portugues: {
        my_profession: "Desenvolvedor Fullstack",
        profile_details: "Detalhes de Perfil",
        skills: {
          skill: "Conhecimentos",
          skills: [
            "Visual Studio Code",
            "HTML",
            "CSS",
            "JavaScript",
            "Vue Js 3",
            "Vue Router 4",
            "Vuex 4",
            "PHP 8",
            "Laravel 8",
            "MySql",
            "MariaDB",
            "Npm",
            "Composer",
            "Packagist",
            "Rest API",
            "Git",
            "cPanel",
            "Cron Job",
            "POO",
            "XML",
            "JSON",
            "ECMAScript",
            "UI",
            "UX",
          ],
        },
        about: {
          about: "Sobre min",
          address: {
            from: {
              from: "Sou de ",
              city: "Gramado RS, BR",
              google_maps: "https://goo.gl/maps/GH2JP18Sbxo4axmVA",
            },
            current: {
              lives_in: "Moro em",
              city: "Roma, IT",
              google_maps: "https://goo.gl/maps/Hc7UpuLZ2FjeEmLo9",
            },
          },
          work_at: {
            work_at: "Trabalho em",
            company: "Sellmasters",
            site: "https://www.sellmasters.it/",
          },
        },
        social_media: "Mídias Sociais",
      },
      italiano: {
        my_profession: "Sviluppatore Fullstack",
        profile_details: "Dettagli del Profilo",
        skills: {
          skill: "Conoscenza",
          skills: [
            "Visual Studio Code",
            "HTML",
            "CSS",
            "JavaScript",
            "Vue Js 3",
            "Vue Router 4",
            "Vuex 4",
            "PHP 8",
            "Laravel 8",
            "MySql",
            "MariaDB",
            "Npm",
            "Composer",
            "Packagist",
            "Rest API",
            "Git",
            "cPanel",
            "Cron Job",
            "POO",
            "XML",
            "JSON",
            "ECMAScript",
            "UI",
            "UX",
          ],
        },
        about: {
          about: "Su di me",
          address: {
            from: {
              from: "Sono nato a",
              city: "Gramado RS, BR",
              google_maps: "https://goo.gl/maps/GH2JP18Sbxo4axmVA",
            },
            current: {
              lives_in: "Vivo a",
              city: "Roma, IT",
              google_maps: "https://goo.gl/maps/Hc7UpuLZ2FjeEmLo9",
            },
          },
          work_at: {
            work_at: "Lavoro a",
            company: "Sellmasters",
            site: "https://www.sellmasters.it/",
          },
        },
        social_media: "Social Media",
      },
    },
  },
  mutations: {},
  getters: {},
  actions: {},
  modules: {},
});
